### ISSUE TITLE
Debian Packages lack a dependency: Termstyle

### ISSUE THREAD

**Issue by dmth** [Intevation/intelmq-mailgen#11]
If mailgen is deployed on a different machine then intelmq, Termstyle is missing.

**Comment by dmth** [comment]
This dependency is still missing.

**Comment by bernhardreiter** [comment]
363f4cb6a745bfb595275867e56a7d182b07dbe3 removes usage of termstyle
so it is not necessary to depend on termstyle anymore.
(https://pypi.python.org/pypi/termstyle/0.1.10 is dormant, so not maintained. It is small enough to just be packaged with intelmq-mailgen, but its only use was in a rare error case, so its removal seemed to be the better option.)
