### ISSUE TITLE
turn intelmq-mailgen into a module to help unit test single functions

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-mailgen#19]
The intelmq-mailgen file contains about 20 functions right now.
In order to be able to write unittests for it, we probably should turn it into a module.

Within the tests directory I would want to import the functions and write tests for it.

e.g. into directory "mailgen" with __init__.py
and turn intelmq-mailgen into file that just imports that module and runs it.

**Comment by bernhardreiter** [comment]
Proposal:
1. We use a [Python Package](https://docs.python.org/3/tutorial/modules.html#packages) as opposed to just one or several Python Module files
Because we will end up with more than one Python Module file over time and there is a good chance that mailgen will continue to be distributed separately. And packages are the commonly used way to distribute Python code.
2. Name ```intelmqmail```.
Because [PEP-8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) recommends: 
> Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

And ```intelmqmail``` is short and more in sync with other intelmq commands and bot names, which usually are like ```intelmqctl``` pder ```intelmqdump``` or have an underscore like ```tor_nodes```.
3. Future packaging with setup.py's [```entry-points``` directive](https://packaging.python.org/distributing/#entry-points)
4. move `__main__ `action into a `main()` function

So the proposed directory structure would be
```
./intelmqmail
    ___init___.py
    intelmqmail.py
```

with 
```python
    entry_points={
        'console_scripts': [
            'intelmqmail = intelmqmail.intelmqmail:main',
        ],

```

**Comment by dmth** [comment]
I'm not familiar enough with python modules. Please be aware of the very similar `intelmailer.sh` https://github.com/certtools/intelmq-mailer/tree/master/src/bin

**Comment by bernhard-herzog** [comment]
> ```
> ./intelmqmail
>     ___init___.py
>     intelmqmail.py
> ```

Using the same name for the package and a module inside the package is confusing. In Python 2 this could even lead to hard-to-debug errors due to relative imports. In Python 3 this shold not be a problem, I think, but it's still strange to have to repeat module names. A better name for the module would be `main.py`

**Comment by bernhardreiter** [comment]
@bernhard-herzog I'm also fine with 
```./intelmqmail
    ___init___.py
   main.py
```

@dmth, I know about intelmqmailer this is a reason to suggest a different name.

**Comment by gsiv** [comment]
In general, I would welcome mailgen becoming a standard Python package.

**Comment by bernhardreiter** [comment]
@gsiv: Is this a go or a not-go on the updated proposal? Do you see any problems?

**Comment by bernhardreiter** [comment]
New suggestion, which I am going to implement.
```
./intelmqmail
    ___init___.py
   cb.py
```

```python
    entry_points={
        'console_scripts': [
            'intelmqcbmail = intelmqmail.cb:main',
        ],
```

Rationale:
* `cb` is more significant than `main` and  it could stand for contactbase or certbund-contactdb
* `intelmqcbmail` is more specific
* Better than "postgres" because there may be different ways to deal with the postgres output
  and the module itself may grow other mail options
* namespace potential to become the "mail" sending package for intelmq

Actually this package depends heavly on certbund-contact, in the future it makes more sense to distribute both, the bot and the mailer within one add-on package for intelmq.

**Comment by bernhard-herzog** [comment]
> cb is more significant than main

`cb` doesn't have any obvious meaning to me. I still think, `main` would be better. Within the context of the `intelmqmail` package it should be specific enough.

**Comment by bernhardreiter** [comment]
@bernhard-herzog I believe 'cb' fits with the short version of the command line and leaves it open to have other commands that make use of additional modules in the packages in the future. Thus we are more flexible with "cb". "main" would have a clear preferance.
