### ISSUE TITLE
mailgen uses only default formating

### ISSUE THREAD

**Issue by swilde** [Intevation/intelmq-mailgen#20]
The current implementation of mailgen can only create two variations
of mails:

1. when the "format" field of the record in the notifications table
   contains "feed_specific" as value, the mail will be created from
   the "specific.txt" template, with cvs data containing
   `botnet_drone_csv_columns'.

2. for any other value of "format" a mail will be generated from the
   template specified in the notification record, with cvs data containing
   `most_csv_columns'.

Looking at the code line 599 ff. this comes to no surprise:

        if notification["format"] == "feed_specific":
            formatter = known_formatters['feed_specific'].get(('csv',
                                                               notification["feed_name"]))
            if formatter is not None:
                formatter = known_formatters['feed_specific'].get(('csv',
                                                                   'DEFAULT'))

        else:
            formatter = known_formatters['generic'].get((notification["format"],
                                                         "GENERIC"))

besides being hilarious the "if formatter is not None:" makes no sense
at all and should be deleted.  The whole
mail_format_feed_specific_as_csv should be deleted, too, as there is
already a generic fallback...

**Comment by dmth** [comment]
I strongly agree on this topic, as `mail_format_feed_specific_as_csv` was just a quick hack to restore basic functionality one or two weeks ago.

**Comment by bernhard-herzog** [comment]
The radical simplification with https://github.com/Intevation/intelmq-mailgen/commit/a055bd58ae1583bbc820f5bf69cc79da22aabd7c should fix this. For now only the feed_specific format is supported anymore with no fallback. See the commit message for some details.
