### ISSUE TITLE
Dokumentation flaws

### ISSUE THREAD

**Issue by swilde** [Intevation/intelmq-mailgen#22]
The documentation needs some cleanup and rework, two especially important points:

* the documentation contains a rather incomprehensible (at least to me) section "Specific Templates". 

* Some CSV output-formaters are using the information from classification identifier as malware name.
  The documentation should explain this fact and point out, that the modify expert should be 
  used to fill the classification identifier with the wanted values.

**Comment by bernhard-herzog** [comment]
The section about "Specific Templates" has been removed with https://github.com/Intevation/intelmq-mailgen/commit/a055bd58ae1583bbc820f5bf69cc79da22aabd7c because the fallback mechanism that this section apparently intended to describe has been removed.

**Comment by gsiv** [comment]
I took a stab at cleaning up the README.

Consider it work in progress.  Please, especially review the section "Preparing Input Data for MailGen".  I didn't touch the section "Developer Information" at all yet.

**Comment by swilde** [comment]
Thanks, IMO the new section fixes the problem.
