### ISSUE TITLE
Packaging-Debian: Leave system configuration untouched

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-mailgen#24]
@gsiv does debian/rules
'''sh
    sed 's@/usr/local/lib/intelmq@/usr/lib/intelmq@' \
          debian/intelmq-mailgen/usr/share/doc/intelmq-mailgen/examples/intelmq-mailgen.conf.example \
          > debian/intelmq-mailgen/etc/intelmq/intelmq-mailgen.conf
'''
leave the system configuration line okay?
(The replacement also seems unnecessary rightn ow.)

**Comment by gsiv** [comment]
On Thu, Jul 07, 2016 at 04:42:20AM -0700, Bernhard E. Reiter wrote:
> @gsiv does debian/rules
> [...]
> leave the system configuration line okay?

Well, it creates the config file in the first place.  Users'
customizations will be handled by dpkg.

**Comment by wagner-intevation** [comment]
This rule entry does no loinger exist. Only an example is installed now:
https://github.com/Intevation/intelmq-mailgen/blob/6a8cb766b46b78466f454890762d170207b131b4/debian/intelmq-mailgen.install#L3
