### ISSUE TITLE
Add a way to send no notifications for selected recipients.

### ISSUE THREAD

**Issue by swilde** [Intevation/intelmq-mailgen#25]
There should be a way to prevent creation of notification mails for certain recipients.
A simple design would be to send no notifications if the `notification-inerval` for the contact is set to `-1`.

**Comment by aaronkaplan** [comment]
> On 28 Jul 2016, at 13:34, Sascha Wilde <notifications@github.com> wrote:
> 
> There should be a way to prevent creation of notification mails for certain recipients.
> A simple design would be to send no notifications if the notification-inerval for the contact is set to -1.
> 

Hi,

did you take a look at our squelcher-expert bot?
https://github.com/certat/intelmq/tree/master/intelmq/bots/experts/squelcher

It supports a config where you can specify "ttl" values how long messages should be suppressed for certain ASNs or net blocks.

Best,
a.

**Comment by swilde** [comment]
@aaronkaplan thanks for pointing this out.  While the bot looks interesting it seems to build upon some design which is orthogonal to the current implementation of the certbund_contact db.  It might be worth to consider merging this different approaches later on, but fo now I will rely on the notification-inerval set by the certbund_contact expert.

**Comment by aaronkaplan** [comment]
---
Mobile

> On 28.07.2016, at 15:50, Sascha Wilde <notifications@github.com> wrote:
> 
> @aaronkaplan thanks for pointing this out. While the bot looks interesting it seems to build upon some design which is orthogonal to the current implementation of the certbund_contact db. It might be worth to consider merging this different approaches later on, but fo now I will rely on the notification-inerval set by the certbund_contact expert.
> 

Okay. :)
As long as you are aware of it. 

Thx
