### ISSUE TITLE
Create a unique ticket number per email usable for help desks

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-mailgen#28]
Each email should have a unique ticket number.
It should be usable for help desks, this means:
* Shorter and readable is better
* should make it hard to guess the number of send reports.

Idea is: use a prefix for the cert, like cert-example "CE"
then an iso like date and a unique random number,
formated to be readable over the phone.

Example
CE-20160818-1234-5678

Variants:
* Using hexadecimal number one could save one character length, which could be used
to make it shorter or to implement a simple checksum to prevent typos

Implementation ideas:
* Use the postgresql database to have a table that marks the randomly chosen ticket ids
to avoid collisions. Could be done by a postgresql internal function.
* use a dict internal to one mailgen run, and limit the mailgen runs to 1 per day
(or add the hours behind the date)
* sync mailgen runs via an extra database (redis?) :)
* add a small service that only draws new unique numbers.

Using postgresql seems to be preferable to not introduce more dependencies. 
If the roundtrip to the db or to the service becomes a problem, someone could draw a couple of ids and cache them for usage.

**Comment by bernhardreiter** [comment]
To caluculate the the danger of collisions, we can use the formular from https://en.wikipedia.org/wiki/Universally_unique_identifier#Random_UUID_probability_of_duplicates

```python
from math import log, exp
def p(n,x):
    return 1 - exp(- (n*n / (2*2**x)))

log(10**8, 2) # bits for 8 decimal digits
p(1000, 26.5) # probability for collisions after 1000 random numbers
p(1000000, 46.5) # probability for collisions after 1m numbers and 46.5 bit length
log(2**46.5,10) # needed decimal digits for 46.5 bits =~14
log(2**46.5,16) # needed hexadecimal digits 
```

So we would need 14 decimal digits or 12 hexadecimal digits to come below 1%.

**Comment by bernhardreiter** [comment]
An idea found by @g-tom:
Use a Feistel-Chiper, see
* http://blog.joevandyk.com/2013/04/18/generating-random-ids-with-postgresql/
* http://wiki.postgresql.org/wiki/Pseudo_encrypt
* https://wiki.postgresql.org/wiki/Pseudo_encrypt_constrained_to_an_arbitrary_range

Before implementing this, it probably needs checking that the 
'round' function is good enough to get pseudo-random values 
and it would need a configuration parameter (a key) to make it unguessable 
as our code is public.

**Comment by dmth** [comment]
> and it would need a configuration parameter (a key) to make it unguessable 

Based on the examples above, I do not understand where such a custom key / seed (?) has to be added.

**Comment by bernhardreiter** [comment]
:/ wrong ticket number in 	68c4e9b

**Comment by gsiv** [comment]
Tested this on Ubuntu (with f08b666) and ran into this problem:

```
$ psql -f /usr/share/intelmq-mailgen/sql/notifications.sql intelmq-events
BEGIN
CREATE ROLE
CREATE ROLE
CREATE ROLE
ALTER DATABASE
ALTER TABLE
SET
GRANT
GRANT
GRANT
CREATE TYPE
CREATE SEQUENCE
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:34: ERROR:  must be member of role "eventdb_send_notifications"
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:39: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:41: ERROR:  syntax error at or near "GRANT"
LINE 2: GRANT SELECT, UPDATE ON ticket_day TO eventdb_send_notificat...
        ^
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:57: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:60: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:62: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:64: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:107: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:132: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:145: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:148: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/usr/share/intelmq-mailgen/sql/notifications.sql:154: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
```

**Comment by bernhardreiter** [comment]
@gsiv improved in 9d49bab391f9aa1d871540df70531cb361159034
