### ISSUE TITLE
Reading of configuration files should be optional

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-mailgen#5]
To enable testing as a regular user, reading the system configuration file should be optional
and if there is a complete system configuration file there is no need to enforce an additional local user
one.

**Comment by dmth** [comment]
This Issue was fixed with: https://github.com/Intevation/intelmq-mailgen/commit/2a5d08b3124dd7d6550c849260f8c754c71f7816

Configuration can now be in two places, but at least one config has to exist.
